// Turns src/data/products.json into seed.sql for D1.
//   npm run db:seed:local    (writes seed.sql, applies to the local database)
//   npm run db:seed:remote   (applies to the deployed database)
//
// Re-runnable: rows are upserted by code, and the owner's in_stock flag is kept
// so a reseed after a price change does not silently put sold-out items back.

import { readFile, writeFile } from "node:fs/promises";

const q = (value) => `'${String(value).replace(/'/g, "''")}'`;

const products = JSON.parse(await readFile("src/data/products.json", "utf8"));

const rows = products.map((p, index) =>
  `(${p.code},${q(p.category)},${q(p.name)},${q(p.unit)},${p.mrp},${p.price},${index})`,
);

const sql = `-- Generated by scripts/generate-seed.mjs. Do not edit by hand.
INSERT INTO products (code, category, name, unit, mrp, price, sort_order)
VALUES
${rows.join(",\n")}
ON CONFLICT(code) DO UPDATE SET
  category   = excluded.category,
  name       = excluded.name,
  unit       = excluded.unit,
  mrp        = excluded.mrp,
  price      = excluded.price,
  sort_order = excluded.sort_order;
`;

await writeFile("seed.sql", sql);
console.log(`Wrote seed.sql with ${products.length} products`);
